data:
  root_dir: "data/raw/mvtec_anomaly_detection"
  category: "bottle"
  img_size: 256

model:
  name: "efficientad"

training:
  batch_size: 1
  num_workers: 4
  learning_rate: 0.0001
  num_epochs: 1

efficientad:
  train_batch_size: 1
  eval_batch_size: 32

evaluation:
  metrics: ["auroc", "pixel_auroc"]

output:
  experiment_dir: "experiments/efficientad"
  save_images: true
